# required - Provide the authentication token available at http://ibm.biz/A11yToolsLandingPage
# i.e: authToken: 00000000-0000-0000-0000-000000000000/00000000-0000-0000-0000-000000000000
# Note: authToken for user mcmdev@us.ibm.com
authToken: 1364f334-0b01-44fc-ba77-b48558be6cce/e9764f3a-6efb-42b7-b8dc-e20ac4bde181

# optional - Specify the rule pack server to use. (Where to pull the rules and engine from)
# Default: https://cc-rules.w3ibm.mybluemix.net/js/latest/
rulePack: https://cc-rules.w3ibm.mybluemix.net/js/latest/

# optional - Specify the rule archive
# i.e. For May rule archive use ruleArchive: 2017MayDeploy
# Default: latest
# Refer to README.md FAQ section below to get the rule archive ID.
ruleArchive : 2018AugustDeploy


# optional - Specify one or many policies to scan.
# i.e. For one policy use policies: CI162_5_2_DCP080115
# i.e. Multiple policies: CI162_5_2_DCP080115,CI162_5_2_DCP070116 or refer to below as a list
# Default: null (all policies)
#
policies:
  - IBM_Accessibility_2018_08

# optional - Specify one or many violation levels on which to fail the test
#            i.e. If specified violation then the testcase will only fail if
#                 a violation is found during the scan.
# i.e. failLevels: violation
# i.e. failLevels: violation,potential violation or refer to below as a list
# Default: violation, potentialviolation
failLevels:
    - violation

# optional - Specify one or many violation levels which should be reported
#            i.e. If specified violation then in the report it would only contain
#                 results which are level of violation.
# i.e. reportLevels: violation
# i.e. reportLevels: violation,potentialviolation or refer to below as a list
# Default: violation, potentialviolation, recommendation, potentialrecommendation, manual
reportLevels:
    - violation
    - potentialviolation

# Optional - Which type should the results be outputted to
#   outputFormat: json
# Default: json
outputFormat:
    - json

# Optional - Specify labels that you would like associated to your scan
#
# i.e.
#   label: Firefox,master,V12,Linux
#   label:
#       - Firefox
#       - master
#       - V12
#       - Linux
# Default: N/A
label:
    - master

disable:
    # FIXME - Disabled these rules for the initial CI/CD integration.
    - 488
    - 495

# optional - Where the scan results should be saved.
# Default: results
outputFolder: ./test-output/a11y

# optional - Should Hidden content be scanned
# true --> Yes scan hidden content
# false --> Don't scan hidden content
# Default: false
checkHiddenContent: false