sudo: required
services:
  - docker
  - xvfb

language: node_js
node_js:
  - "10"

git:
  submodules: false

branches:
  only:
    - master
    - /^[0-9]+\..*$/
    - /^v[0-9]+\..*$/
    - /^release-[0-9]+\..*$/

env:
  global:
    - COMPONENT_TAG_EXTENSION="-${TRAVIS_COMMIT}"
    - COMPONENT_INIT_COMMAND=${TRAVIS_BUILD_DIR}/build/install-dependencies.sh
    - COMPONENT_BUILD_COMMAND=${TRAVIS_BUILD_DIR}/build/build.sh
    - COMPONENT_UNIT_TEST_COMMAND=${TRAVIS_BUILD_DIR}/build/run-unit-tests.sh
    - COMPONENT_E2E_TEST_COMMAND=${TRAVIS_BUILD_DIR}/build/run-e2e-tests.sh

stages:
  - unit-test
  - build
  - test-e2e
  - publish

before_script:
  - make init

jobs:
  include:
    - stage: unit-test
      name: "Run linting"
      if: type = pull_request
      script:
        - make show-env
        - make jq/install
        - make jq/search
