sudo: required
services:
  - docker
  - xvfb

cache:
  apt: true
  directories:
    - "$TRAVIS_CACHE_DIR"

before_cache:
  - sudo rm -rf $TRAVIS_CACHE_DIR/selenium-standalone

notifications:
  email: false

git:
  submodules: false

branches:
  only:
    - master
    - /^[0-9]+\..*$/
    - /^v[0-9]+\..*$/
    - /^release-[0-9]+\..*$/

matrix:
  include:
    # --- Just linting ---
  - stage: linting
    name: "Push linting"
    os: linux
    language: node_js
    node_js:
      - "10"
    env:
      - JOBNAME=AMD64
    before_install:
      - make init
    install: 
      - make download-plugins
      - make install-proxy
    script:
      - make lint-proxy

  # --- Integration testing ---
  - stage: test-pr
    name: "PR tests"
    if: type = pull_request
    os: linux
    dist: trusty
    language: node_js
    addons:
      chrome: stable
    node_js:
      - "10"
    env:
      - JOBNAME=AMD64 DOCKER_TAG=$(git log -1 --pretty="%aN" | sed 's/[^a-zA-Z0-9]*//g')
    before_install:
      - make init
      - make test-module
      - make docker-logins
      - make download-clis
    install:
      - make install
    before_script:
      - make webpack
      - make headless
      - make build-image
    script:
      - make tests-dev
    after_success:
      - make release
    after_failure:
      - make release
      - cat client/selenium-debug.log

  # --- x86 Deploy to Artifactory ---
  - stage: build
    name: "Build x86"
    if: (branch = master) AND (type = push)
    os: linux
    language: node_js
    node_js:
      - "10"
    env:
      - JOBNAME=AMD64 PUSH_REPO=integration 
    before_install:
      - make init
      - make docker-login
      - make download-clis
    install:
      - make install
    script:
      - make webpack
      - make headless
      - make build-image
      - make release
      - make release PUSH_RHEL=true
      - make release DOCKER_TAG=latest
      - make release DOCKER_TAG=latest-rhel

  # -- PPC Deploy to Artifactory ---
  - stage: build
    name: "Build PPC"
    if: (branch = master) AND (type = push)
    os: linux-ppc64le
    language: node_js
    node_js:
      - "10"
    env:
      - JOBNAME=Power PUSH_REPO=integration 
    before_install:
      - make init
      - make docker-login
      - make download-clis
    install:
      - make install
    script:
      - make webpack
      - make headless
      - make build-image
      - make release
      - make release DOCKER_TAG=latest



 # -- s390x Deploy to Artifactory ---
  - stage: build
    name: "Build s390x"
    if: (branch = master) AND (type = push)
    os: linux-s390
    language: node_js
    node_js:
      - "10"
    env:
      - JOBNAME=s390x PUSH_REPO=integration 
    before_install:
      - make init
      - make docker-logins
      - make download-clis
    install:
      - make install
    script:
      - make webpack
      - make headless
      - make build-image
      - make release
      - make release DOCKER_TAG=latest